## CERTBOT
# sudo certbot certonly --webroot -w /var/www/easydbrest.com/public -d easydbrest.com
## MKCERT
# mkcert -key-file /etc/mkcert/certs/easydbrest.com/privkey.pem -cert-file /etc/mkcert/certs/easydbrest.com/fullchain.pem easydbrest.com app.easydbrest.com local.easydbrest.com '*.easydbrest.com'

server {
    listen 80;
    server_name easydbrest.com www.easydbrest.com app.easydbrest.com local.easydbrest.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name easydbrest.com www.easydbrest.com app.easydbrest.com local.easydbrest.com;
    root /var/www/projects/easy-db-rest/public;

    charset utf-8;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    ssl_certificate /etc/certs/easydbrest.com/fullchain.pem;
    ssl_certificate_key /etc/certs/easydbrest.com/privkey.pem;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;

        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~ /\.ht {
        deny all;
    }
}
