server {
    listen 80;
    server_name meuhost.com www.meuhost.com;
    root /var/www/projects/issue-mapper/public;

    index index.php index.html index.htm;

    location / {
        autoindex on;
        try_files $uri $uri/ /index.php?$query_string;
    }

   location / {
       try_files $uri $uri/ =404;
   }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~ /\.ht {
        deny all;
    }
}
