
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    charset utf-8;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    root /var/www/html;
    index index.php index.htm index.html;

    ## Your domains
    server_name app.easydbrest.tiagofranca.com app.easydbrest.com local.dbrest.com;

    ## mkcert -key-file /etc/mkcert/certs/easydbrest.com/privkey.pem -cert-file /etc/mkcert/certs/easydbrest.com/fullchain.pem app.easydbrest.tiagofranca.com app.easydbrest.com local.dbrest.com '*.dbrest.com'
    ssl_certificate /etc/mkcert/certs/easydbrest.com/fullchain.pem;
    ssl_certificate_key /etc/mkcert/certs/easydbrest.com/privkey.pem;

    if ($http_x_forwarded_proto = 'http' ) {
        return 301 https://$host$request_uri;
    }

    location ~ /.well-known {
        allow all;
    }

    location / {
        ## Your app base url (target to proxy)
        proxy_pass http://127.0.0.1:8000;

        client_max_body_size 100M;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        ## Assegura que o caminho, URI e query string sejam passados corretamente
        proxy_redirect off;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}
